# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: true

os:
  - linux
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; 
      then 
        sudo apt-get update -qq ;
        sudo apt-get install -y dcmtk ;
    fi
  - if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; 
    then 
      brew install -v dcmtk ;
    fi  

after_success:
  - Rscript -e 'covr::coveralls()'